Traceback (most recent call last):
  File "C:\Users\valer\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\valer\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\valer\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\valer\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\valer\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\valer\Anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\valer\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\valer\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%load_ext nb_black
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-2-50ec12b286b4>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mget_ipython[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mrun_line_magic[0m[1;33m([0m[1;34m'load_ext'[0m[1;33m,[0m [1;34m'nb_black'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py[0m in [0;36mrun_line_magic[1;34m(self, magic_name, line, _stack_depth)[0m
[0;32m   2346[0m                 [0mkwargs[0m[1;33m[[0m[1;34m'local_ns'[0m[1;33m][0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mget_local_scope[0m[1;33m([0m[0mstack_depth[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2347[0m             [1;32mwith[0m [0mself[0m[1;33m.[0m[0mbuiltin_trap[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2348[1;33m                 [0mresult[0m [1;33m=[0m [0mfn[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2349[0m             [1;32mreturn[0m [0mresult[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2350[0m [1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\decorator.py[0m in [0;36mfun[1;34m(*args, **kw)[0m
[0;32m    230[0m             [1;32mif[0m [1;32mnot[0m [0mkwsyntax[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    231[0m                 [0margs[0m[1;33m,[0m [0mkw[0m [1;33m=[0m [0mfix[0m[1;33m([0m[0margs[0m[1;33m,[0m [0mkw[0m[1;33m,[0m [0msig[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 232[1;33m             [1;32mreturn[0m [0mcaller[0m[1;33m([0m[0mfunc[0m[1;33m,[0m [1;33m*[0m[1;33m([0m[0mextras[0m [1;33m+[0m [0margs[0m[1;33m)[0m[1;33m,[0m [1;33m**[0m[0mkw[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    233[0m     [0mfun[0m[1;33m.[0m[0m__name__[0m [1;33m=[0m [0mfunc[0m[1;33m.[0m[0m__name__[0m[1;33m[0m[1;33m[0m[0m
[0;32m    234[0m     [0mfun[0m[1;33m.[0m[0m__doc__[0m [1;33m=[0m [0mfunc[0m[1;33m.[0m[0m__doc__[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\IPython\core\magic.py[0m in [0;36m<lambda>[1;34m(f, *a, **k)[0m
[0;32m    185[0m     [1;31m# but it's overkill for just that one bit of state.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m    186[0m     [1;32mdef[0m [0mmagic_deco[0m[1;33m([0m[0marg[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 187[1;33m         [0mcall[0m [1;33m=[0m [1;32mlambda[0m [0mf[0m[1;33m,[0m [1;33m*[0m[0ma[0m[1;33m,[0m [1;33m**[0m[0mk[0m[1;33m:[0m [0mf[0m[1;33m([0m[1;33m*[0m[0ma[0m[1;33m,[0m [1;33m**[0m[0mk[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    188[0m [1;33m[0m[0m
[0;32m    189[0m         [1;32mif[0m [0mcallable[0m[1;33m([0m[0marg[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\IPython\core\magics\extension.py[0m in [0;36mload_ext[1;34m(self, module_str)[0m
[0;32m     31[0m         [1;32mif[0m [1;32mnot[0m [0mmodule_str[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     32[0m             [1;32mraise[0m [0mUsageError[0m[1;33m([0m[1;34m'Missing module name.'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 33[1;33m         [0mres[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mshell[0m[1;33m.[0m[0mextension_manager[0m[1;33m.[0m[0mload_extension[0m[1;33m([0m[0mmodule_str[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     34[0m [1;33m[0m[0m
[0;32m     35[0m         [1;32mif[0m [0mres[0m [1;33m==[0m [1;34m'already loaded'[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\IPython\core\extensions.py[0m in [0;36mload_extension[1;34m(self, module_str)[0m
[0;32m     78[0m             [1;32mif[0m [0mmodule_str[0m [1;32mnot[0m [1;32min[0m [0msys[0m[1;33m.[0m[0mmodules[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     79[0m                 [1;32mwith[0m [0mprepended_to_syspath[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mipython_extension_dir[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 80[1;33m                     [0mmod[0m [1;33m=[0m [0mimport_module[0m[1;33m([0m[0mmodule_str[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     81[0m                     [1;32mif[0m [0mmod[0m[1;33m.[0m[0m__file__[0m[1;33m.[0m[0mstartswith[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mipython_extension_dir[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     82[0m                         print(("Loading extensions from {dir} is deprecated. "

[1;32m~\Anaconda3\lib\importlib\__init__.py[0m in [0;36mimport_module[1;34m(name, package)[0m
[0;32m    125[0m                 [1;32mbreak[0m[1;33m[0m[1;33m[0m[0m
[0;32m    126[0m             [0mlevel[0m [1;33m+=[0m [1;36m1[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 127[1;33m     [1;32mreturn[0m [0m_bootstrap[0m[1;33m.[0m[0m_gcd_import[0m[1;33m([0m[0mname[0m[1;33m[[0m[0mlevel[0m[1;33m:[0m[1;33m][0m[1;33m,[0m [0mpackage[0m[1;33m,[0m [0mlevel[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    128[0m [1;33m[0m[0m
[0;32m    129[0m [1;33m[0m[0m

[1;32m~\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_gcd_import[1;34m(name, package, level)[0m

[1;32m~\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_find_and_load[1;34m(name, import_)[0m

[1;32m~\Anaconda3\lib\importlib\_bootstrap.py[0m in [0;36m_find_and_load_unlocked[1;34m(name, import_)[0m

[1;31mModuleNotFoundError[0m: No module named 'nb_black'
ModuleNotFoundError: No module named 'nb_black'

