Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
frequency, wavenumber, momentum, energy = p1()

print(f"The frequency of a photon with wavelength 486.1 nm is {frequency} Hz.")
print(f"The wavenumber, nu-bar, of a photon with wavelength  486.1 nm is {wavenumber} cm^-1.")
print(f"The momentum of a photon with wavelength  486.1 nm is {momentum} kg m/s.")
print(f"The energy of a photon with wavelength  486.1 nm is {energy} Joules.")

assert(isinstance(frequency,float)), "Type Error: The frequency should be a float."
assert(isinstance(wavenumber,float)), "Type Error: The wavenumber should be a float."
assert(isinstance(momentum,float)), "Type Error: The momentum should be a float."
assert(isinstance(energy,float)), "Type Error: The energy should be a float."

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m/var/folders/gf/7vfqp7nn2972hrcz727tkjkh0000gn/T/ipykernel_54054/865377954.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mprint[0m[0;34m([0m[0;34mf"The energy of a photon with wavelength  486.1 nm is {energy} Joules."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0;32massert[0m[0;34m([0m[0misinstance[0m[0;34m([0m[0mfrequency[0m[0;34m,[0m[0mfloat[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m [0;34m"Type Error: The frequency should be a float."[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;32massert[0m[0;34m([0m[0misinstance[0m[0;34m([0m[0mwavenumber[0m[0;34m,[0m[0mfloat[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m [0;34m"Type Error: The wavenumber should be a float."[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;32massert[0m[0;34m([0m[0misinstance[0m[0;34m([0m[0mmomentum[0m[0;34m,[0m[0mfloat[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m [0;34m"Type Error: The momentum should be a float."[0m[0;34m[0m[0;34m[0m[0m

[0;31mAssertionError[0m: Type Error: The frequency should be a float.
AssertionError: Type Error: The frequency should be a float.

